#!/bin/sh

cd "$HOME"

# Initializing submodules
yadm submodule update --init

# Linking NvChad config
ln -sf $HOME/.config/nvchad $HOME/.config/nvim/lua/custom

# Installing fish plugins
fish -c 'curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher && fisher update'
