import = [
  "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[window]
opacity = 0.84
startup_mode = "Maximized"

[font]
size = 16

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true
